services:
  chatservice:
    build :
      context: .
      dockerfile: Dockerfile    
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/chatdb
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8083:8083
    networks:
      - foundit-network
    
networks:
  foundit-network:
    driver: bridge

volumes:
  postgres:
    driver: local